#!/usr/local/bin/perl
#
# Test tool: Fills RC Dashboard database with dummy data
#

$|++;
use strict;
use warnings;
use Carp;
use Data::Dumper;
use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../lib/perl";
use lib "$FindBin::Bin/../bin/admin/bin";
use ariba::rc::dashboard::Config;
use ariba::rc::dashboard::Constants;
use ariba::rc::dashboard::DB;
use Sys::Hostname;

my $config = new ariba::rc::dashboard::Config();
my $derp = $config->parse();
my $db = new ariba::rc::dashboard::DB();
my $now = time() - 1200;
			
foreach my $b ("Typhoon-2725", "Voyageurs-666")
{
	foreach my $m ("compile", "archive", "push", "qual")
	{
		foreach my $s ("start", "end")
		{
			my $status = $s eq "start" && $m eq "qual" && $b eq "Voyageurs-666" ? "running" : "success";
			my $start_date = $now;
			$now += 50 + int (rand (50));
			my $end_date = $s eq "end" ? $now : 0;
	
			my $res = $db->insert 
			(
				{
					'buildname' => $b,
					'milestone' => $m,
					'start_date' => $start_date, 
					'end_date' => $end_date,
					'status' => $status,
			        'hostname' => hostname,
					'logfile' => 'foo', 
				}
			);
			last if ($m eq "qual" && $b eq "Voyageurs-666");
		}
	}
}

my $res = $db->insert 
			(
				{
					'buildname' => 'Voyageurs-666',
					'milestone' => 'qual',
					'start_date' => 0,
					'end_date' => $now - 1,
					'status' => 'success',
			        'hostname' => hostname,
					'logfile' => 'foo',
				}
			);
print "$res\n";
my $timeline = $db->fetch (100);
print Dumper ($timeline);


